# Site settings
title: SNOWiQ User Manual
author: 
name: EastBanc Technologies
description: "SNOWiQ User Manual | eastbanctech.com"
email: contact@eastbanctech.com
webpage: https://eastbanctech.com/

plugins:
  - jekyll-remote-theme
  - "jekyll-seo-tag"



#google analytics
ga_tracking: G-WV1WXP9LB7
ga_tracking_anonymize_ip: true


# Build settings
remote_theme: pmarsceill/just-the-docs

color_scheme: foo

# Aux links for the upper right navigation
aux_links:
  "Powered by TERRAiQ":
    - "https://eastbanctech.com/products/terraiq/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

search_enabled: true
search:
  previews: 2
  previews_words_before: 2
  previews_words_after: 5
  # Display the relative url in search results
  rel_url: true
